#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("StockSuggest.Droid.Resource", IsApplication=true)]

namespace StockSuggest.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040004
			public const int counter_text_bg = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int counter_text_color = 2130968581;
			
			// aapt resource value: 0x7f040001
			public const int list_background = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int list_background_pressed = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int list_divider = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int list_item_title = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int card_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int counter_bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int drawer_list_item_bg_normal = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int drawer_list_item_bg_pressed = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int drawer_list_selector = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_drawer_dark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_drawer_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_home = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_picks = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_portfolio = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_watchlist = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Icon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int monoandroidsplash = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000e
			public const int content = 2131165198;
			
			// aapt resource value: 0x7f070005
			public const int counter = 2131165189;
			
			// aapt resource value: 0x7f07000d
			public const int drawer_layout = 2131165197;
			
			// aapt resource value: 0x7f070000
			public const int editText1 = 2131165184;
			
			// aapt resource value: 0x7f07000f
			public const int left_drawer = 2131165199;
			
			// aapt resource value: 0x7f070002
			public const int listViewPicks = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int listicon = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int relativeLayout1 = 2131165190;
			
			// aapt resource value: 0x7f07000c
			public const int textChange = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int textExchange = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int textSep = 2131165194;
			
			// aapt resource value: 0x7f070007
			public const int textStockName = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int textStockPrice = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int textSymbol = 2131165193;
			
			// aapt resource value: 0x7f070001
			public const int textView1 = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int title = 2131165188;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int fragment_home = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int fragment_picks = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int listmenu = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int listview_picks = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int drawer_close = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int drawer_open = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Mono_Android_Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
